config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'pages#index'

  resources :profiles 
  resources :categories
  resources :orders, only: [:index]

  resources :products do
    resources :posts
    resources :questions
    resources :orders, only: [:show, :new, :create, :edit, :update, :destroy]
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorie.rb
class Categorie < ApplicationRecord
	mount_uploader :photo, PhotoUploader
	has_many :products
#	belongs_to :admin_user
#	validates :name, :photo, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
    belongs_to :product
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploaders :images, PhotoUploader
	serialize :images, JSON # If you use SQLite, add this line.

	belongs_to :categorie
    has_many :posts
    has_many :questions
    has_many :orders
end

app/models/profile.rb
class Profile < ApplicationRecord
	mount_uploader :avatar, PhotoUploader

	belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
    belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :posts
  has_many :questions
  has_many :orders
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_user!
before_action :set_product
	
  def index
  	@orders = current_user.orders
  end

  def new
    @order = Order.new
  end
  
  def create
    params[:order][:product_id] = @product.id
    @order = current_user.orders.build(order_params)
    if @order.save
      redirect_to product_path(@product.id)
    else
      render 'new'
    end    
  end
    
private
  def set_product
    @product = Product.find_by(id: params[:product_id])
  end
  
  def order_params
    params.require(:order).permit(:user_id, :product_id, :comment, :ordercount)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	if user_signed_in? and current_user.profile.nil?
  		redirect_to new_profile_path
  	end
  	@categories = Categorie.all

  	if user_signed_in? 
  		@orders 
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :set_product

  def new
    @comment = Post.new
  end
  
  def create
    params[:post][:product_id] = @product.id
    @comment = current_user.posts.build(post_params)
    if @comment.save
      redirect_to product_path(@product.id)
    else
      render 'new'
    end
    
  end
    
private
  def set_product
    @product = Product.find_by(id: params[:product_id])
  end
  
  def post_params
    params.require(:post).permit(:user_id, :product_id, :body)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
  	@product = Product.find_by(id: params[:id])
    @comments = @product.posts
    @questions = @product.questions
  end

end

app/controllers/profile_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!
  def new
  	@profile = Profile.new
  end

  def create
  	@profile = current_user.build_profile(profile_params)
  	if @profile.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def show
  	@profile = Profile.find_by(id: params[:id])
  end

  def edit
  	@profile = Profile.find_by(id: params[:id])
  end

  def update
  	@profile = Profile.find_by(id: params[:id])
    if @profile.update(profile_params)
  		redirect_to profile_path(@profile.id)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @profile = Profile.find_by(id: params[:id])
  	@profile.destroy 
  	redirect_to root_path
  end

private 
  def profile_params
  	params.require(:profile).permit(:user_id, :nickname, :age, :avatar)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!

  def new
  	@profile = Profile.new
  end

  def create
  	@profile = current_user.build_profile(profile_params)
  	if @profile.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def show
  	@profile = Profile.find_by(id: params[:id])
  end

  def edit
  	@profile = Profile.find_by(id: params[:id])
  end

  def update
  	@profile = Profile.find_by(id: params[:id])
    if @profile.update(profile_params)
  		redirect_to profile_path(@profile.id)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @profile = Profile.find_by(id: params[:id])
  	@profile.destroy 
  	redirect_to root_path
  end

private 
  def profile_params
  	params.require(:profile).permit(:user_id, :name, :phone, :address, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/orders/index.html.erb
<% if @orders == [] %>

	<p> You have no orders <p>

<% else %>
	Your Orders:<br />
	<% @orders.each do |order| %>
	    <h2><%= link_to order.product.name, product_path(order.product.id) %></h2>
		Count: <%= order.ordercount %><br>
		Comment: <%= order.comment %><br>

		<hr>
	<% end %>
<% end %>

app/views/orders/new.html.erb
<%= form_for @order, url: product_orders_path(@product.id) do |f| %>
  Your Order: <br>
  Count: <%= f.text_field :ordercount %><br />
  Comment: <%= f.text_area :comment, size: "30x10" %><br />
  <%= f.submit "Send" %>
<% end %>

app/views/orders/show.html.erb
Count: <%= order.ordercount %><br>
Comment: <%= order.comment %><br>

app/views/posts/new.html.erb
<%= form_for @comment, url: product_posts_path(@product.id) do |f| %>
  Comment: <%= f.text_area :body, size: "30x10" %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/products/show.html.erb
	<p>
		<% @product.images.each do |image| %>
		   <%= image_tag(image.url, size: "46x46") %>
		<% end %><br>
		Product: <%= @product.name %><br>	
		Price: <%= @product.price %><br>	
		Description: <%= @product.description %><br>	
		Count of product: <%= @product.pcount %><br>	
	</p>

<%= link_to 'Write comment', new_product_post_path(@product.id) %> |
<%= link_to 'Write question', new_product_question_path(@product.id) %> |
<%= link_to 'Order a product', new_product_order_path(@product.id) %><br>

----------------------------------<br>

<% @comments.each do |comment| %>
Comment: <%= comment.body %><br>
<% end %>

----------------------------------<br>

<% @questions.each do |question| %>
Question: <%= question.body %><br>
<% end %>